### ISSUE TITLE
Closing " at end of comment line not included

### ISSUE THREAD

**Issue by johan-groenenboom** [criccomini/proto-schema-parser#32]
I noticed that a comment such as:  
// rpc_response_type = "test/types/v1/test_response.proto"  
will have a node.text equal to:  
// rpc_response_type = "test/types/v1/test_response.proto  
This means for instance, that removing comments from the original text based on the collection of comment nodes does not work.

(tested with 1.3.5 and 1.3.7)

**Comment by criccomini** [comment]
Fixed and released in 1.3.8:

https://pypi.org/project/proto-schema-parser/1.3.8/

**Comment by johan-groenenboom** [comment]
Thanks for the blazingly fast response, it works correctly now!
