### ISSUE TITLE
Generator turns message options into string

### ISSUE THREAD

**Issue by johan-groenenboom** [criccomini/proto-schema-parser#40]
An option definiton can be a message with fields, e.g. a version and an exception_type field:
```
    def test_parser_generator_transparency_for_options(self):
        from proto_schema_parser.parser import Parser
        from proto_schema_parser.generator import Generator
        SCHEMA_TEXT = '''service TestService {
  option (test.options.v1.service) = {
  version: { major: 1 minor: 0 patch: 0 pre_release: "alpha" }
  exception_type: "test.types.v1.Exception"};
  rpc TestMethod (TestRequest) returns (TestResponse);
}'''
        ast = Parser().parse(SCHEMA_TEXT)
        print(Generator().generate(ast))
        self.assertEqual(Generator().generate(ast), SCHEMA_TEXT)

```

This test fails, as the generated option has quotes around the braces that enclose the message, as can be seen from the printed output:
```
test_parser_generator_transparency_for_options (test_schema_parser.TestSchemaParser) ... service TestService {
  option (test.options.v1.service) = "{
  version: { major: 1 minor: 0 patch: 0 pre_release: "alpha" }
  exception_type: "test.types.v1.Exception"}";
  rpc TestMethod (TestRequest) returns (TestResponse);
}
```

**Comment by criccomini** [comment]
Yes, I haven't implemented the part that handles message literals. The grammar is:

```
optionValue: scalarValue | messageLiteralWithBraces;

messageLiteralWithBraces: L_BRACE messageTextFormat R_BRACE;

messageTextFormat: ( ( messageLiteralField ( COMMA | SEMICOLON )? ) | commentDecl ) *;

messageLiteralField: messageLiteralFieldName COLON value |
                       messageLiteralFieldName messageValue;

messageLiteralFieldName: fieldName |
                           L_BRACKET specialFieldName R_BRACKET;

specialFieldName       : extensionFieldName | typeURL;

extensionFieldName     : qualifiedIdentifier;

typeURL                : qualifiedIdentifier SLASH qualifiedIdentifier;

value         : scalarValue | messageLiteral | listLiteral;

messageValue  : messageLiteral | listOfMessagesLiteral;

messageLiteral: messageLiteralWithBraces |
                  L_ANGLE messageTextFormat R_ANGLE;

listLiteral: L_BRACKET ( listElement ( COMMA listElement )* )? R_BRACKET;

listElement: scalarValue | messageLiteral;

listOfMessagesLiteral: L_BRACKET ( messageLiteral ( COMMA messageLiteral )* )? R_BRACKET;

messageDecl: MESSAGE messageName L_BRACE messageElement* R_BRACE;
```

As you can see, it gets quite complex. Definitely doable, but I haven't spent the time on it. I'll poke at it, but no promises.

**Comment by johan-groenenboom** [comment]
I appreciate the complexity or novelty compared to the rest of the grammer - these are a bunch of literals rather than definitions.
Adding this at some point would indeed be very nice - currently I'm using some RE to do specific parsing of the internals of the message.
My ticket was actually only intending to ask for a smaller first step - avoiding the quotes around the re-generated message.

**Comment by criccomini** [comment]
@johan-groenenboom I think I've got the parser and generator updated to properly support message literals in option values in https://github.com/criccomini/proto-schema-parser/pull/41. Building a release now.

**Comment by criccomini** [comment]
@johan-groenenboom I just published 1.4.0 here: https://pypi.org/project/proto-schema-parser/1.4.0/

Please let me know how it goes. Closing this for now. We can re-open if you discover issues.

**Comment by johan-groenenboom** [comment]
Hi Chris, I think I'm running into a python version compatibility issue again:
  File "C:\Python38\lib\site-packages\proto_schema_parser\generator.py", line 241, in Generator
    self, elements: list[ast.MessageValue], indent_level: int
TypeError: 'type' object is not subscriptable

**Comment by johan-groenenboom** [comment]
I also noticed that for options the field node.element.name has brackets around the string, is this intentional or should this be considered an issue?

**Comment by criccomini** [comment]
> Hi Chris, thanks again for your efforts. I think I'm running into a python version compatibility issue again: File "C:\Python38\lib\site-packages\proto_schema_parser\generator.py", line 241, in Generator self, elements: list[ast.MessageValue], indent_level: int TypeError: 'type' object is not subscriptable

Ah, my bad. Sorry about that. Fixed here: https://github.com/criccomini/proto-schema-parser/pull/42

> I also noticed that for options the field node.element.name has brackets around the string, is this intentional or should this be considered an issue? For me the brackets were unexpected - should I submit another issue for this?

You're talking about the generator, right? Can you give me an example of what you mean?

**Comment by johan-groenenboom** [comment]
Thanks for that fix - it works - will you release a new version for it?

> > I also noticed that for options the field node.element.name has brackets around the string, is this intentional or should this be considered an issue? For me the brackets were unexpected - should I submit another issue for this?
> 
> You're talking about the generator, right? Can you give me an example of what you mean?

```
proto_text = """
service TestService {
    option (test.major_version) = 1;
}
"""
syntax_tree = Parser().parse(proto_text)
for node in syntax_tree.file_elements:
    if isinstance(node, ast.Service):
        for element in node.elements:
            print(element)
```

gives the following output:
```
Option(name='(test.major_version)', value=1)
```

I suppose the name of the option should be 'test.major_version' without the brackets?

**Comment by criccomini** [comment]
> Option names refer to fields on the various concrete options messages, described in more detail in the next section below. Parenthesized names refer to extension fields. An extension on one of the concrete option types is also called a "custom option".

Hmm, yea, TIL. I'm open to whatever you prefer. In the meantime, I'll cut a release.

**Comment by criccomini** [comment]
Ok, I've published 1.4.1:

https://pypi.org/project/proto-schema-parser/1.4.1/

Should have the latest fixes. :)

**Comment by johan-groenenboom** [comment]
Thanks for the new release, it helps me to move forward with my project!

For a more limited sub-topic of the hairy topic of option naming : if an option has a parenthesized name with spaces inside the parentheses, e.g. "(  my.options.v1.service  )", then, with the current parser, the name field of the parsed element will come out exactly like that, including the spaces. This makes it more difficult to look for an option with a specific name, as it can be "spelled" with so many white space variations. So having the parser remove that whitespace would be a useful feature / improvement?

**Comment by criccomini** [comment]
Actually, just pushed a fix here:

https://github.com/criccomini/proto-schema-parser/commit/37287dc84ca6ae6a596484bd58890ca1328c3fe2

**Comment by criccomini** [comment]
1.4.2 has been published with name normalization. :)

https://pypi.org/project/proto-schema-parser/1.4.2/

**Comment by johan-groenenboom** [comment]
I have integrated version 1.4.2 and everything works fine. If I'm not mistaken I have all I need for my application to work - so  thanks again for the fixes, and being so responsive!
